### ISSUE TITLE
Bash IDE extension in VsCode: WebAssembly Error

### ISSUE THREAD

**Issue by mdeberts** [bash-lsp/bash-language-server#1247]
### Code editor

VsCode 1.96.1

### Platform

Remote SSH to a HPC which runs Red Hat Enterprise Linux release 8.8

### Version

5.4.2 (node:4132222) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created)

### What steps will reproduce the bug?

Install VsCode Extension called Bash IDE on Remote SSH machine
Go to Output Window, read Error

### How often does it reproduce? Is there a required condition?

Happens every start

### What is the expected behavior?

Bash IDE extension should load

### What do you see instead?

Error message in Output of Remote SSH:
```
[15:56:29.139] [server] [14:56:27] [<unknown>][2c08909f][ExtensionHostConnection] <284654><stderr> rejected promise not handled within 1 second: RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
[15:56:29.140] [server] stack trace: RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
[15:56:29.141] [server]     at lazyllhttp (/hpc/uhome/mdeberts/.vscode-server/cli/servers/Stable-42b266171e51a016313f47d0c48aca9295b9cbb2/server/node_modules/undici/lib/dispatcher/client-h1.js:79:28)
[15:56:29.142] [server] 
```

Error message in Output of Bash IDE
```
/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320
const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
                     ^

RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/editorconfig/lib/index.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.18.1
[Error - 2:56:31 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:56:31 PM] Connection to server got closed. Server will restart.
true
[Error - 2:56:31 PM] Bash IDE client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320
const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
                     ^

RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/editorconfig/lib/index.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.18.1
[Error - 2:56:32 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:56:32 PM] Connection to server got closed. Server will restart.
true
[Error - 2:56:32 PM] Bash IDE client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:56:32 PM] Start failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320
const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
                     ^

RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/editorconfig/lib/index.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.18.1
[Error - 2:56:32 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:56:32 PM] Connection to server got closed. Server will restart.
true
[Error - 2:56:32 PM] Bash IDE client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:56:32 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320
const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
                     ^

RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/editorconfig/lib/index.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.18.1
[Error - 2:56:32 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 2:56:32 PM] Connection to server got closed. Server will restart.
true
[Error - 2:56:32 PM] Bash IDE client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:56:32 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320
const wasmInstance = new WebAssembly.Instance(wasmModule, imports);
                     ^

RangeError: WebAssembly.Instance(): Out of memory: Cannot allocate Wasm memory for new instance
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/@one-ini/wasm/one_ini.js:320:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/hpc/uhome/mdeberts/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.43.0/node_modules/editorconfig/lib/index.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.18.1
[Error - 2:56:33 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:56:33 PM] The Bash IDE server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 2:56:33 PM] Bash IDE client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:56:33 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by skovhus** [comment]
Please re-open if this is still the case.
