### ISSUE TITLE
Checksum error on npm install

### ISSUE THREAD

**Issue by mikehaertl** [bash-lsp/bash-language-server#296]
```
# sudo -i
# npm i -g bash-language-server
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! code EINTEGRITY
npm ERR! sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA== integrity checksum failed when using sha512: wanted sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
/usr/local/bin/bash-language-server -> /usr/local/lib/node_modules/bash-language-server/bin/main.js
+ bash-language-server@1.17.0
added 115 packages from 220 contributors in 4.522s
npm ERR! Callback called more than once.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-22T06_31_41_199Z-debug.log
```

Relevant part from root log:
```
[...]
380 verbose stack Error: sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA== integrity checksum failed when using sha512: wanted sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
380 verbose stack     at IntegrityStream.[_onEnd] (/usr/share/nodejs/ssri/index.js:86:19)
380 verbose stack     at IntegrityStream.emit (/usr/share/nodejs/ssri/index.js:59:35)
380 verbose stack     at IntegrityStream.[maybeEmitEnd] (/usr/share/nodejs/ssri/node_modules/minipass/index.js:350:12)
380 verbose stack     at IntegrityStream.end (/usr/share/nodejs/ssri/node_modules/minipass/index.js:230:27)
380 verbose stack     at PassThrough.onend (_stream_readable.js:672:10)
380 verbose stack     at Object.onceWrapper (events.js:286:20)
380 verbose stack     at PassThrough.emit (events.js:198:13)
380 verbose stack     at endReadableNT (_stream_readable.js:1145:12)
380 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
381 verbose cwd /root
382 verbose Linux 5.4.0-74-generic
383 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "bash-language-server"
384 verbose node v10.19.0
385 verbose npm  v6.14.4
386 error code EINTEGRITY
387 error sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA== integrity checksum failed when using sha512: wanted sha512-v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
388 verbose exit [ 1, true ]
```

**Comment by skovhus** [comment]
I cannot reproduce this anymore.
