### ISSUE TITLE
Error on startup using built-in nvim lsp-server

### ISSUE THREAD

**Issue by nwithers-ecr** [bash-lsp/bash-language-server#319]
Client crashes immediately on opening any file with `.sh` extension, even if the file is empty. 

# lspconfig

```lua
local lsp_root = '/home/nwithers/.local/share/nvim/lsp_servers'
local opts = {}
if server.name == 'bashls' then
  local bashls_root_dir = lsp_root .. '/bash/node_modules/bash-language-server'
  local bashls_binary = bashls_root_dir .. '/bin/main.js'
  opts.cmd = { bashls_binary, 'start' }
  opts.root_dir = function()
    return bashls_root_dir
  end
end
server:setup(opts)
```

# $HOME/.cache/nvim/lsp.log
```
[START][2021-12-09 10:33:50] LSP logging initiated
[ERROR][2021-12-09 10:33:52] .../vim/lsp/rpc.lua:412    "rpc"   "/home/nwithers/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/bin/main.js"       "stderr"        '/home/nwithers/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1
```
```js
var Module=void
0!==Module?Module:{};
!function(e,t){
  "function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()(0,function(){var e,t={};
  for(e in Module)
    Module.hasOwnProperty(e)&&(t[e]=Module[e]);
    var r,n,s=[],o="./this.program",_=function(e,t){throw t},a=!1,u=!1 a="object"==typeof window,u="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n=!a&&!r&&!u;
    var i,l,d,c,m,f="";
    r?(f=u?require("path").dirname(f)+"/":__dirname+"/",i=function(e,t){return c||(c=require("fs")),m||(m=require("path")),e=m.normalize(e),c.readFileSync(e,t?null:"utf8")},d=function(e){var t=i(e,!0);
  return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(o=process.argv[1].replace(/\\\\/g,"/")),s=process.argv.slice(2),"undefined"!=typeof module&&(module.expo
```
```
TypeError: WebAssembly.Global is not a constructor
    at /home/nwithers/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:12512
    at /home/nwithers/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144
    at Object.<anonymous> (/home/nwithers/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:170)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
'
```

**Comment by nwithers-ecr** [comment]
It appears this issue is resolved as I am using a very outdated version of node. 
Currently using v10.19.0, but after installing v17.2.0 the issue no longer exists

**Comment by EricDriussi** [comment]
Well, I'm on `v17.3.0` and I'm getting pretty much the same mistake :thinking: :
```
TypeError: WebAssembly.Global is not a constructor\n    
  at /home/eric/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:12512\n    
  at /home/eric/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144\n    
  at Object.<anonymous> (/home/eric/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:170)\n  
  at Module._compile (internal/modules/cjs/loader.js:778:30)\n   
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    
  at Module.load (internal/modules/cjs/loader.js:653:32)\n   
  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n   
  at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n   
  at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n'

```
