### ISSUE TITLE
Spawning language server with cmd: `bash-language-server` failed.

### ISSUE THREAD

**Issue by lucasgrvarela** [bash-lsp/bash-language-server#339]
I'm using Linux Mint 20.3 (Una) and NVIM v0.6.1 with LuaJIT 2.1.0-beta3 with the plugins nvim-lspconfig and nvim-lsp-installer.

When opening a bash file I receive the following error:
```
Spawning language server with cmd: `bash-language-server` failed. The language server is either not installed, missing from PATH, or not executable.                                
Client 2 quit with exit code 1 and signal 0
```

On the logs I got this error:
```
cat ~/.cache/nvim/lsp.log

[ERROR][2022-03-08 22:07:09] .../vim/lsp/rpc.lua:420	"rpc"	"bash-language-server"	"stderr"	'/home/user/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);var r,n,s=[],o="./this.program",_=function(e,t){throw t},a=!1,u=!1;a="object"==typeof window,u="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n=!a&&!r&&!u;var i,l,d,c,m,f="";r?(f=u?require("path").dirname(f)+"/":__dirname+"/",i=function(e,t){return c||(c=require("fs")),m||(m=require("path")),e=m.normalize(e),c.readFileSync(e,t?null:"utf8")},d=function(e){var t=i(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(o=process.argv[1].replace(/\\\\/g,"/")),s=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=

TypeError: WebAssembly.Global is not a constructor
    at /home/user/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:12512
    at /home/user/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144
    at Object.<anonymous> (/home/user/.local/share/nvim/lsp_servers/bash/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:170)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)'
```

**Comment by lucasgrvarela** [comment]
For anyone with the same problem using Linux Mint or Ubuntu just run the code in code block below, it will install the LTS version of Node (16.14.0 as today), that version is recommended by the majority of the LSP servers.

```
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by cblessing24** [comment]
The following command fixed the issue for me on Arch:
`sudo pacman -S nodejs-lts-gallium`
