### ISSUE TITLE
[Bug] SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by luiz00martins** [bash-lsp/bash-language-server#428]
After installing with `sudo npm i -g bash-language-server`, I got the following error upon running `bash-language-server`:
```
/usr/local/lib/node_modules/bash-language-server/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/bash-language-server/node_modules/vscodejsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

-----
Info:
 - `Pop!_OS 22.04 LTS x86_64`
 - `npm 8.5.1`
 - `node 12.22.9`

**Comment by luiz00martins** [comment]
The actual problem presented when I tried to update npm:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vscode-jsonrpc@8.0.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
```
Basically, Ubuntu's version of NodeJS is too dated (as usual).

You can solve the problem by [installing to the latest verson of node](https://askubuntu.com/a/548776), and trying again:
```bash
# Install latest version of node.
curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt-get install -y nodejs

# Update bash-language-server.
sudo npm update --location=global

# Test bash-language-server.
bash-language-server -v
```
