### ISSUE TITLE
TypeError: folders is not iterable

### ISSUE THREAD

**Issue by Shane-XB-Qian** [bash-lsp/bash-language-server#516]
```log
/usr/local/lib/node_modules/bash-language-server/out/linter.js:58
            for (const folder of folders) {
                                 ^

TypeError: folders is not iterable
    at Linter.<anonymous> (/usr/local/lib/node_modules/bash-language-server/out/linter.js:58:34)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/bash-language-server/out/linter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/bash-language-server/out/linter.js:4:12)
    at Linter.runShellcheck (/usr/local/lib/node_modules/bash-language-server/out/linter.js:56:16)
    at Linter.<anonymous> (/usr/local/lib/node_modules/bash-language-server/out/linter.js:31:39)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/bash-language-server/out/linter.js:8:71
    at new Promise (<anonymous>)
```

bash-language-server --version
Version is 3.1.0

**Comment by Shane-XB-Qian** [comment]
```diff
diff --git a/server/src/linter.ts b/server/src/linter.ts
index 0f78c64..29c5f63 100644
--- a/server/src/linter.ts
+++ b/server/src/linter.ts
@@ -60,14 +60,16 @@ export default class Linter {
   private async runShellcheck(
     executablePath: string,
     document: LSP.TextDocument,
     folders: LSP.WorkspaceFolder[],
   ): Promise<ShellcheckResult> {
     const args = ['--format=json1', '--external-sources', `--source-path=${this.cwd}`]
-    for (const folder of folders) {
-      args.push(`--source-path=${folder.name}`)
+    if (Array.isArray(folders)) {
+      for (const folder of folders) {
+        args.push(`--source-path=${folder.name}`)
+      }
     }
 
     let out = ''
     let err = ''
     const proc = new Promise((resolve, reject) => {
       const proc = spawn(executablePath, [...args, '-'], { cwd: this.cwd })
```

**Comment by skovhus** [comment]
Thanks for reporting this. I'm having a hard time reproducing this. Can you show a reproducible example?

**Comment by Shane-XB-Qian** [comment]
i trying to debug a bit, pls check the comments in #535

**Comment by skovhus** [comment]
Closed as this was a problem with an LSP client.
