### ISSUE TITLE
unrecognized option `--source-path=undefined'

### ISSUE THREAD

**Issue by alikthename** [bash-lsp/bash-language-server#586]
Hi, with emacs 28.2, lspj-mode, and bash-language-server this is what I get on language server start:

*lsp-log*

```Command "/home/alik/.emacs.d/.cache/lsp/npm/bash-language-server/bin/bash-language-server start" is present on the path.
Command "/home/alik/.emacs.d/.cache/lsp/npm/bash-language-server/bin/bash-language-server start" is present on the path.
Found the following clients for /home/alik/my/test/home/apps/jack_start_zita-a2j.sh: (server-id bash-ls, priority -1)
The following clients were selected based on priority: (server-id bash-ls, priority -1)
Initialized server v. 3.3.1 for file:///mnt/win_f/ali/zotero/zotero/my/test
BackgroundAnalysis: resolving glob "**/*@(.sh|.inc|.bash|.command)" inside "/mnt/win_f/ali/zotero/zotero/my/test"...
BackgroundAnalysis: Glob resolved with 32 files after 0.375 seconds
BackgroundAnalysis: Completed after 0.489 seconds.
onDocumentSymbol
onDocumentHighlight 0:0 word="#!/usr/bin/env bash"
onDocumentSymbol
onDocumentHighlight 0:0 word="#!/usr/bin/env bash"
```

*bash-ls::stderr*

```

/home/alik/tmp/.emacs.d/.cache/lsp/npm/bash-language-server/lib/node_modules/bash-language-server/out/linter.js:104
                throw new Error(`ShellCheck: json parse failed with error ${e}\nout:\n${out}\nerr:\n${err}`);
                      ^

Error: ShellCheck: json parse failed with error SyntaxError: Unexpected end of JSON input
out:

err:
unrecognized option `--source-path=/mnt/win_f/ali/zotero/zotero/my/test'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'
unrecognized option `--source-path=undefined'

Usage: shellcheck [OPTIONS...] FILES...
  -a                --check-sourced          Include warnings from sourced files
  -C[WHEN]          --color[=WHEN]           Use color (auto, always, never)
  -e CODE1,CODE2..  --exclude=CODE1,CODE2..  Exclude types of warnings
  -f FORMAT         --format=FORMAT          Output format (checkstyle, gcc, json, tty)
  -s SHELLNAME      --shell=SHELLNAME        Specify dialect (sh, bash, dash, ksh)
  -V                --version                Print version information
  -x                --external-sources       Allow 'source' outside of FILES


    at Linter.<anonymous> (/home/alik/tmp/.emacs.d/.cache/lsp/npm/bash-language-server/lib/node_modules/bash-language-server/out/linter.js:104:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/alik/tmp/.emacs.d/.cache/lsp/npm/bash-language-server/lib/node_modules/bash-language-server/out/linter.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.4.0

Process bash-ls stderr finished
```

**Comment by skovhus** [comment]
I tried fixing this in `bash-language-server@4.0.0-beta.1` (that now requires node >= 14, hence the new 4.0 and the beta tag). It has not been released in the vscode extension yet.

@alikthename can you test it out and report back if it works for you? There is also additional debug logging.

**Comment by alikthename** [comment]
> I tried fixing this in `bash-language-server@4.0.0-beta.1` (that now requires node >= 14, hence the new 4.0 and the beta tag). It has been released as the vscode extension version 1.18.0.
> 
> @alikthename can you test it out and report back if it works for you? There is also additional debug logging.

I don't quite see how to compile/install this. I cloned the repo with corresponding commit/tag, what should I do next? Please also keep in mind I'm using it with emacs and lsp-mode, not vscode. Though I can test it with vscode as well if I have instruction

**Comment by skovhus** [comment]
Thanks. You don’t need to clone the repository. I assume you normally install bash-language-server using npm when using emacs?

To install the beta release `npm i -g bash-language-server@4.0.0-beta.1`

**Comment by alikthename** [comment]
ok, did just that and the output now is:
*lsp-log*:
```
Command "/usr/bin/bash-language-server start" is present on the path.
Command "/usr/bin/bash-language-server start" is present on the path.
Found the following clients for /mnt/win_f/ali/zotero/zotero/my/test/home/apps/jack_start_zita-a2j.sh: (server-id bash-ls, priority -1)
The following clients were selected based on priority: (server-id bash-ls, priority -1)
Initialized server v. 4.0.0-beta.1 for file:///mnt/win_f/ali/zotero/zotero/my/test/home/apps
BackgroundAnalysis: resolving glob "**/*@(.sh|.inc|.bash|.command)" inside "/mnt/win_f/ali/zotero/zotero/my/test/home/apps"...
BackgroundAnalysis: Glob resolved with 14 files after 0.027 seconds
BackgroundAnalysis: Completed after 0.063 seconds.
```


*bash-ls::stderr*



```

Process bash-ls stderr finished
/usr/lib/node_modules/bash-language-server/out/linter.js:76
                if (folder.name.trim()) {
                                ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at Linter.<anonymous> (/usr/lib/node_modules/bash-language-server/out/linter.js:76:33)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/bash-language-server/out/linter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/bash-language-server/out/linter.js:4:12)
    at Linter.runShellcheck (/usr/lib/node_modules/bash-language-server/out/linter.js:62:16)
    at Linter.<anonymous> (/usr/lib/node_modules/bash-language-server/out/linter.js:33:39)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/bash-language-server/out/linter.js:8:71
    at new Promise (<anonymous>)

Node.js v17.4.0

Process bash-ls stderr finished
/usr/lib/node_modules/bash-language-server/out/linter.js:76
                if (folder.name.trim()) {
                                ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at Linter.<anonymous> (/usr/lib/node_modules/bash-language-server/out/linter.js:76:33)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/bash-language-server/out/linter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/bash-language-server/out/linter.js:4:12)
    at Linter.runShellcheck (/usr/lib/node_modules/bash-language-server/out/linter.js:62:16)
    at Linter.<anonymous> (/usr/lib/node_modules/bash-language-server/out/linter.js:33:39)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/bash-language-server/out/linter.js:8:71
    at new Promise (<anonymous>)

Node.js v17.4.0

Process bash-ls stderr finished
```

**Comment by skovhus** [comment]
Thanks!

**Comment by alikthename** [comment]
version 3.3.1 works if I remove shellcheck from system packages  (the system is debian-10)
but version 4.0.0-beta.1 crashes either way with the above output

**Comment by skovhus** [comment]
Thanks! Odd that the workspace folder name is undefined, that could be a bug in the emacs LSP client as the types should ensure that it is always defined.

Can you try the new version `npm i -g bash-language-server@4.0.0-beta.2` and past the log output? We should now never crash if the ShellCheck fails and we should handle the folder name being `undefined`.

**Comment by alikthename** [comment]
installed bash-language-server@4.0.0-beta.2
now it starts without crashing, but gives an error:
```
Error while linting: TypeError: Cannot read properties of undefined (reading 'trim')
```
and error checking actually  does not take place

**Comment by skovhus** [comment]
My bad, can you try `npm install -g bash-language-server@4.0.0-beta.3`?

**Comment by alikthename** [comment]
> My bad, can you try `npm install -g bash-language-server@4.0.0-beta.3`?

 yes, here is the output:
```ShellCheck: running "shellcheck --shell=bash --format=json1 --external-sources --source-path=/mnt/win_f/ali/zotero/zotero/my/test/home/apps"
Error while linting: Error: ShellCheck: json parse failed with error SyntaxError: Unexpected end of JSON input
out:

err:
unrecognized option `--source-path=/mnt/win_f/ali/zotero/zotero/my/test/home/apps'

Usage: shellcheck [OPTIONS...] FILES...
  -a                --check-sourced          Include warnings from sourced files
  -C[WHEN]          --color[=WHEN]           Use color (auto, always, never)
  -e CODE1,CODE2..  --exclude=CODE1,CODE2..  Exclude types of warnings
  -f FORMAT         --format=FORMAT          Output format (checkstyle, gcc, json, tty)
  -s SHELLNAME      --shell=SHELLNAME        Specify dialect (sh, bash, dash, ksh)
  -V                --version                Print version information
  -x                --external-sources       Allow 'source' outside of FILES

```

**Comment by skovhus** [comment]
Can you try `shellcheck --version`. I assume this is an older version (< `0.8`)

**Comment by alikthename** [comment]
> Can you try `shellcheck --version`. I assume this is an older version (< `0.8`)

Installed version 0.8, now it works and lsp shows errors, thanks a lot
