### ISSUE TITLE
env `BACKGROUND_ANALYSIS_MAX_FILES` cannot be set

### ISSUE THREAD

**Issue by psydvl** [bash-lsp/bash-language-server#631]
## Details
Environment variable `BACKGROUND_ANALYSIS_MAX_FILES` cannot be set because "Expected number, received string" error raised  
bash variable are untyped, so it should be parsed as number any way

```
LSP-bash: /home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/zod/lib/types.js:29
LSP-bash:         const error = new ZodError_1.ZodError(ctx.common.issues);
LSP-bash:                       ^
LSP-bash: 
LSP-bash: ZodError: [
LSP-bash:   {
LSP-bash:     "code": "invalid_type",
LSP-bash:     "expected": "number",
LSP-bash:     "received": "string",
LSP-bash:     "path": [
LSP-bash:       "backgroundAnalysisMaxFiles"
LSP-bash:     ],
LSP-bash:     "message": "Expected number, received string"
LSP-bash:   }
LSP-bash: ]
LSP-bash:     at handleResult (/home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/zod/lib/types.js:29:23)
LSP-bash:     at ZodObject.safeParse (/home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/zod/lib/types.js:142:16)
LSP-bash:     at ZodObject.parse (/home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/zod/lib/types.js:122:29)
LSP-bash:     at Object.getConfigFromEnvironmentVariables (/home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/bash-language-server/out/config.js:52:41)
LSP-bash:     at BashServer.<anonymous> (/home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/bash-language-server/out/server.js:113:84)
LSP-bash:     at Generator.next (<anonymous>)
LSP-bash:     at /home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/bash-language-server/out/server.js:8:71
LSP-bash:     at new Promise (<anonymous>)
LSP-bash:     at __awaiter (/home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/bash-language-server/out/server.js:4:12)
LSP-bash:     at /home/nixi/.cache/sublime-text/Package Storage/LSP-bash/19.1.0/language-server/node_modules/bash-language-server/out/server.js:112:40 {
LSP-bash:   issues: [
LSP-bash:     {
LSP-bash:       code: 'invalid_type',
LSP-bash:       expected: 'number',
LSP-bash:       received: 'string',
LSP-bash:       path: [ 'backgroundAnalysisMaxFiles' ],
LSP-bash:       message: 'Expected number, received string'
LSP-bash:     }
LSP-bash:   ],
LSP-bash:   addIssue: [Function (anonymous)],
LSP-bash:   addIssues: [Function (anonymous)],
LSP-bash:   errors: [
LSP-bash:     {
LSP-bash:       code: 'invalid_type',
LSP-bash:       expected: 'number',
LSP-bash:       received: 'string',
LSP-bash:       path: [ 'backgroundAnalysisMaxFiles' ],
LSP-bash:       message: 'Expected number, received string'
LSP-bash:     }
LSP-bash:   ]
LSP-bash: }
LSP-bash: 
LSP-bash: Node.js v19.1.0
```

## System info 
bash-language-server version: Version is 4.1.2
node version: v19.1.0
plugin: [LSP-bash](https://github.com/sublimelsp/LSP-bash) 1.1.15
Editor: Sublime Text Build 4143
system: openSUSE Tumbleweed 20221212-0 x86_64

**Comment by jfcherng** [comment]
This should've been fixed as of LSP-bash v`2.0.0` by migrating settings from "env" to "settings".
