### ISSUE TITLE
Server does not work at all

### ISSUE THREAD

**Issue by bli00** [bash-lsp/bash-language-server#698]
### Code editor

Sublime Text 4

### Platform

MacOs 13.1

### Version

Crashes

### What steps will reproduce the bug?

Any command on`bash-language-server`

### What do you see instead?

I see the following crash error for any commands given to `bash-language-server`, even the `-v` flag:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:child_process'
Require stack:
- /usr/local/lib/node_modules/bash-language-server/out/server.js
- /usr/local/lib/node_modules/bash-language-server/out/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/bash-language-server/out/server.js:12:30)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/bash-language-server/out/server.js',
    '/usr/local/lib/node_modules/bash-language-server/out/cli.js'
  ]
}
```

**Comment by skovhus** [comment]
Which version of node are you using? `node —version`? Node version 14 is required.

**Comment by bli00** [comment]
> Which version of node are you using? `node —version`? Node version 14 is required.

I'm using node `v14.16.0`

**Comment by skovhus** [comment]
So it seems the node import protocol was introduced with node v14.18.0. https://nodejs.org/api/esm.html#node-imports

But note that node 14 is end of life 30 April 2023.

**Comment by bli00** [comment]
https://github.com/bash-lsp/bash-language-server/pull/699
