### ISSUE TITLE
TypeError: Failed to parse URL from /usr/local/lib/node_modules/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm

### ISSUE THREAD

**Issue by avatar-lavventura** [bash-lsp/bash-language-server#733]
### Code editor

emacs

### Platform

macOS

### Version

Version is 2.0.0

### What steps will reproduce the bug?

 bash-language-server --help

### How often does it reproduce? Is there a required condition?

always

### What do you see instead?

 bash-language-server --help

```bash
Usage:
  bash-language-server start
  bash-language-server -h | --help
  bash-language-server -v | --version

node:internal/deps/undici/undici:11404
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /usr/local/lib/node_modules/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11404:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:6996:25)
      at fetch2 (node:internal/deps/undici/undici:10545:25)
      at Object.fetch (node:internal/deps/undici/undici:11402:18)
      at fetch (node:internal/process/pre_execution:241:25)
      at /usr/local/lib/node_modules/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:15041
      at /usr/local/lib/node_modules/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:15262
      at /usr/local/lib/node_modules/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144 {
    input: '/usr/local/lib/node_modules/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v19.6.1
```

**Comment by skovhus** [comment]
So which version of bash-language-server have you installed?

**Comment by avatar-lavventura** [comment]
The version I have installed was: Version is 4.7.0. But this issue is resolved when I try to install in inside the emacs (which asks automatically when it couldn't find the `bash-language-server` binary.)
