### ISSUE TITLE
Constantly Bombarded by Error Message: Request textDocument/hover failed.

### ISSUE THREAD

**Issue by lamyergeier** [bash-lsp/bash-language-server#907]
### Code editor

Codium

### Platform

Fedora 38

### Version

v1.38.0

### What do you see instead?

![image](https://github.com/bash-lsp/bash-language-server/assets/42092626/d4739d6b-7ba1-4205-aa4b-d0767f089ee5)

### Additional information

`bashIde.explainshellEndpoint` is blank in the Settings

Issue started randomly from today.

**Comment by skovhus** [comment]
That is odd. Can you provide a code example?

**Comment by skovhus** [comment]
Can you reproduce this with the newest server version (5.0)?

**Comment by corneliusroemer** [comment]
I'm getting the same bug on the latest version v1.41.0 using language server v5.2.0 on macOS VSCode 1.91

It makes the extensions fully unusable unfortunately (I love it in general!)

**Comment by mwinters-stuff** [comment]
I am getting the same errors, using "latest" v1.41.0, also with the same errors as above.. 

The project, has quite a lot of scripts (617), which "all" seem to be scanned even when "never" opened...

**Comment by schrummy14** [comment]
I have also begun to get these "memory access out of bounds" messages when working with shell scripts.
Using server v1.41.0 on Fedora 40.

**Comment by SplitGemini** [comment]
+1

**Comment by lamyergeier** [comment]
Again facing it today

![image](https://github.com/user-attachments/assets/86790aac-abdb-45c2-a954-973dc3bf458f)

**Comment by gissf1** [comment]
I'm also getting these errors rather frequently, but its been happening for 6 months or longer.  I don't think it's platform specific, but I'm on Arch Linux with VS-codium v1.92.2-24228 and Bash IDE v1.38.0.  I use many shell scripts in my various projects, so this plugin is generally of great help to my day.

This issue seems to get triggered when there is a syntax error in the script (like if you make an "if" without a matching "fi" or mismatched parenthesis / curly braces), then move your cursor around the script in random places.  I'll try to be more mindful of a pattern that triggers it and report back if I discover specific steps to consistently reproduce the issue.

As a workaround, I sometimes disable and re-enable the plugin, or if that fails, often restarting the IDE helps.

**Comment by skovhus** [comment]
> I'll try to be more mindful of a pattern that triggers it and report back if I discover specific steps to consistently reproduce the issue.

That would be great. Having a hard time reproducing this.

**Comment by gissf1** [comment]
OK, it just triggered again for me.  Not quite a reproducer, but I seem to at least have a backtrace.

I got these error messages on the console (I just SNIPed my home directory path from the messages):
```
[Error - 2:50:48 PM] Unhandled Rejection at promise: [object Promise], reason: RuntimeError: memory access out of bounds
    at wasm://wasm/000b627a:wasm-function[236]:0x2a422
    at Parser.parse (SNIP/.vscode-oss/extensions/mads-hartmann.bash-ide-vscode-1.38.0-universal/node_modules/web-tree-sitter/tree-sitter.js:1:53101)
    at Analyzer.analyze (SNIP/.vscode-oss/extensions/mads-hartmann.bash-ide-vscode-1.38.0-universal/node_modules/bash-language-server/out/analyser.js:47:34)
    at BashServer.<anonymous> (SNIP/.vscode-oss/extensions/mads-hartmann.bash-ide-vscode-1.38.0-universal/node_modules/bash-language-server/out/server.js:241:45)
    at Generator.next (<anonymous>)
    at SNIP/.vscode-oss/extensions/mads-hartmann.bash-ide-vscode-1.38.0-universal/node_modules/bash-language-server/out/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (SNIP/.vscode-oss/extensions/mads-hartmann.bash-ide-vscode-1.38.0-universal/node_modules/bash-language-server/out/server.js:4:12)
    at BashServer.analyzeAndLintDocument (SNIP/.vscode-oss/extensions/mads-hartmann.bash-ide-vscode-1.38.0-universal/node_modules/bash-language-server/out/server.js:238:16)
    at SNIP/.vscode-oss/extensions/mads-hartmann.bash-ide-vscode-1.38.0-universal/node_modules/bash-language-server/out/server.js:122:22
[Error - 2:50:48 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603 
[Error - 2:50:48 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603 
[Error - 2:50:48 PM] Request textDocument/documentHighlight failed.
  Message: Request textDocument/documentHighlight failed with message: memory access out of bounds
  Code: -32603 
[Error - 2:51:53 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: memory access out of bounds
  Code: -32603 
[Error - 2:51:53 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: memory access out of bounds
  Code: -32603 
```

I was typing this line within a shell script function on line 584:
```
	DB_PASSWORDS=$( echo -e "$DB_PASSWORDS" | sed -r 's///g' )
```

I had typed the line and moved my text cursor back with the arrow keys to the `s///g` regex part between the first and second slash, intending to fill it in.

After it triggers, the problem happens almost continuously just by moving the mouse cursor over the code text.  I assume it's looking for some tooltip text to pop up and failing to get that due to some inconsistent internal state.

Disabling the plugin, restarting plugins, and then reenabling it restored normal operation.

Backspacing the line from the end and re-typing it did not re-trigger the issue.

Getting it to happen from a fresh start is not so easy.  Seems to happen most often after I've been working for a while.

I'll report back again if I find anything else.

**Comment by skovhus** [comment]
The stack-trace indicates that it could be an issue with treesitter. I just upgraded to the latest version, and released a new LSP version 5.4.2 and vscode extension 1.43. Let me know if it fixes anything.

**Comment by gissf1** [comment]
> > latest version v1.41.0 using language server v5.2.0 on macOS VSCode 1.91
> 
> You're lucky, the version on https://open-vsx.org/extension/mads-hartmann/bash-ide-vscode is still stuck on 1.38.0

For what it's worth, the updated plugin isn't showing for me in VS Codium either.

According to the open-vsx website, 1.38.0 is still the latest: https://open-vsx.org/extension/mads-hartmann/bash-ide-vscode

I see 1.43 here: https://marketplace.visualstudio.com/items?itemName=mads-hartmann.bash-ide-vscode but that isn't very easy to install in VS Codium.

@skovhus Any chance you could update on open-vsx too?  Or are they just slow to update their listed versions?

In the meantime, I'm trying a workaround to install v1.43.0, and I'll report back if I can provide more feedback on this issue.

**Comment by gissf1** [comment]
ok, coming back to this, I was able to get v1.43 installed in VS Codium via the `VSIX Manager` plugin, (available here: https://open-vsx.org/extension/zokugun/vsix-manager).

Thus far, over the course of a few weeks, I have not had a single crash or error message since installing this update.  So from that perspective, I think this issue may be fixed in v1.43!

That said, it would be nice if this updated release were available in the open-vsx marketplace as well, since it currently only provides access to v1.38 and older releases, which means anyone using these older versions are likely to find their way to this bug report when they encounter the issue.  The open-vsx page for the extension (the open-vsx.org URL linked in my last post) says it has no owner, and requests that someone claim it.  I imagine anyone using a variant of VS Code that isn't a Microsoft release version would be using the open-vsx marketplace rather than the official VS Code marketplace.

For more information on claiming the plugin, I found this link: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Thanks for the help, and hopefully my reply here can help others as well!

**Comment by CJ-Abrams** [comment]
For whoever is still having the same issue with the latest BashIDE VSCode extension (v1.43), a partial workaround could be to use an extension like `reload`, from [https://marketplace.visualstudio.com/items?itemName=natqe.reload](https://marketplace.visualstudio.com/items?itemName=natqe.reload) (source at [https://github.com/natqe/reload](https://github.com/natqe/reload)), which allows fast-reloading of the editor and all installed extensions, without having to manually quit and restart it completely, keeping the main UI opened and restoring all opened tabs and files in their last state before reloading.

So as soon as the discussed error re-occurs, just click the `reload` button on the bottom-right corner, and you will be able to continue working after a few seconds.

Note: Extension tested and still working in latest VSCode/VSCodium version (v1.97.0 at the time of writing).

**Comment by skovhus** [comment]
I can't reproduce. Please re-open if this still happens.
