### ISSUE TITLE
Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by guoh27** [bash-lsp/bash-language-server#935]
### Code editor

Visual Studio Code

### Platform

Linux

### Version

Vscode plugin version 1.39

### How often does it reproduce? Is there a required condition?

Everyday

### What is the expected behavior?

VScode no error popups

### What do you see instead?

[Error - 3:39:04 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:06 PM] Unhandled Rejection at promise: [object Promise], reason: RuntimeError: memory access out of bounds
    at wasm://wasm/000b627a:wasm-function[236]:0x2a422
    at Parser.parse (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/web-tree-sitter/tree-sitter.js:1:53101)
    at Analyzer.analyze (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/analyser.js:47:34)
    at BashServer.<anonymous> (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:241:45)
    at Generator.next (<anonymous>)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:4:12)
    at BashServer.analyzeAndLintDocument (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:238:16)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:122:22
[Error - 3:39:06 PM] Unhandled Rejection at promise: [object Promise], reason: RuntimeError: memory access out of bounds
    at wasm://wasm/000b627a:wasm-function[236]:0x2a422
    at Parser.parse (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/web-tree-sitter/tree-sitter.js:1:53101)
    at Analyzer.analyze (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/analyser.js:47:34)
    at BashServer.<anonymous> (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:241:45)
    at Generator.next (<anonymous>)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:4:12)
    at BashServer.analyzeAndLintDocument (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:238:16)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:122:22
[Error - 3:39:07 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:07 PM] Unhandled Rejection at promise: [object Promise], reason: RuntimeError: memory access out of bounds
    at wasm://wasm/000b627a:wasm-function[236]:0x2a422
    at Parser.parse (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/web-tree-sitter/tree-sitter.js:1:53101)
    at Analyzer.analyze (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/analyser.js:47:34)
    at BashServer.<anonymous> (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:241:45)
    at Generator.next (<anonymous>)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:4:12)
    at BashServer.analyzeAndLintDocument (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:238:16)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:122:22
[Error - 3:39:07 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:07 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:09 PM] Unhandled Rejection at promise: [object Promise], reason: RuntimeError: memory access out of bounds
    at wasm://wasm/000b627a:wasm-function[236]:0x2a422
    at Parser.parse (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/web-tree-sitter/tree-sitter.js:1:53101)
    at Analyzer.analyze (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/analyser.js:47:34)
    at BashServer.<anonymous> (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:241:45)
    at Generator.next (<anonymous>)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:4:12)
    at BashServer.analyzeAndLintDocument (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:238:16)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:122:22
[Error - 3:39:09 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:10 PM] Unhandled Rejection at promise: [object Promise], reason: RuntimeError: memory access out of bounds
    at wasm://wasm/000b627a:wasm-function[236]:0x2a422
    at Parser.parse (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/web-tree-sitter/tree-sitter.js:1:53101)
    at Analyzer.analyze (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/analyser.js:47:34)
    at BashServer.<anonymous> (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:241:45)
    at Generator.next (<anonymous>)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:4:12)
    at BashServer.analyzeAndLintDocument (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:238:16)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:122:22
[Error - 3:39:10 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:12 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:15 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:21 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:27 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: memory access out of bounds
  Code: -32603 
[Error - 3:39:31 PM] Unhandled Rejection at promise: [object Promise], reason: RuntimeError: memory access out of bounds
    at wasm://wasm/000b627a:wasm-function[236]:0x2a422
    at Parser.parse (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/web-tree-sitter/tree-sitter.js:1:53101)
    at Analyzer.analyze (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/analyser.js:47:34)
    at BashServer.<anonymous> (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:241:45)
    at Generator.next (<anonymous>)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:4:12)
    at BashServer.analyzeAndLintDocument (/home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:238:16)
    at /home/adv-server2/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.39.0/node_modules/bash-language-server/out/server.js:122:22
[Error - 3:39:31 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: memory access out of bounds
  Code: -32603

**Comment by skovhus** [comment]
We have finally upgraded the Bash grammar and the web-tree-sitter runtime in #1146, which should address these “memory access out of bounds” errors.

Please upgrade to the latest version, and don’t hesitate to create a new issue if you still observe any problems. Thanks!
